version: '3.4'

services:
  creativetim.argon.dotnetcore.free:
    image: ${DOCKER_REGISTRY-}creativetimargondotnetcorefree
    build:
      context: .
      dockerfile: CreativeTim.Argon.DotNetCore.Free/Dockerfile
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: 'creativeTim'
      POSTGRES_PASSWORD: 'creativeTim'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgresql-data: