version: '3.4'

services:
  creativetim.argon.dotnetcore.free:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44308
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=host=db;database=creativeTim;user id=creativeTim;password=creativeTim
      - REDIS_INSTANCENAME=redis
    ports:
      - "60151:80"
      - "44308:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro